# Generated by Django 5.1.2 on 2024-10-21 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="место")),
                ("start_time", models.TimeField(verbose_name="время старта")),
                ("action", models.CharField(max_length=300, verbose_name="действие")),
                ("is_pleasant", models.BooleanField(verbose_name="приятная привычка")),
                (
                    "periodicity",
                    models.SmallIntegerField(default=1, verbose_name="периодичность"),
                ),
                (
                    "prize",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="публичная привычка")),
                (
                    "action_time",
                    models.DurationField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="время выполнения",
                    ),
                ),
                (
                    "connected_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
                "ordering": ("start_time",),
            },
        ),
    ]
